name: detective_game_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Providers
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  riverpod_analyzer_utils: ^1.0.0-dev.8

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # Storage and Files
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  
  # Navigation screens
  go_router: ^17.0.0

  # UI
  shimmer: ^3.0.0

  # Utils
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  permission_handler: ^12.0.1
  convert: ^3.1.2
  logger: ^2.6.2

  # QR
  mobile_scanner: ^7.0.0

  # URL Launcher
  url_launcher: ^6.3.1

  # Test
  analyzer: ^8.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.10.5
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^4.0.0+1


flutter:
  # assets:
  #   - assets/episodes/
  #   - assets/episodes/ep_sek_w_tym/ep_sek_w_tym.json
  uses-material-design: true


